#!/bin/sh
#
# Copyright (c) 2021-2023 Franco Fichtner <franco@opnsense.org>
# Copyright (c) 2003 Kenneth R Westerback <krw@openbsd.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# MurOS: ported from FreeBSD ifconfig(8)/route(8)/arp(8) to Linux iproute2.
# Address and route handling now use ip(8); the gateway, DNS and OPNsense
# interface state are still delegated to ifctl/configctl which are
# platform independent helpers.

IP="/sbin/ip"
LOGGER="/usr/bin/logger -s -p user.notice -t dhclient dhclient-script:"

#
# Helper functions that implement common actions.
#

# convert a dotted IPv4 netmask (e.g. 255.255.255.0) to a prefix length (24)
mask2prefix()
{
	local mask="${1:-255.255.255.255}" octet prefix=0
	local IFS=.
	for octet in $mask; do
		case $octet in
		255) prefix=$((prefix + 8));;
		254) prefix=$((prefix + 7));;
		252) prefix=$((prefix + 6));;
		248) prefix=$((prefix + 5));;
		240) prefix=$((prefix + 4));;
		224) prefix=$((prefix + 3));;
		192) prefix=$((prefix + 2));;
		128) prefix=$((prefix + 1));;
		*) ;;
		esac
	done
	echo $prefix
}

delete_old_address()
{
	[ -n "$old_ip_address" ] || return 0
	$IP -4 addr del "$old_ip_address/$(mask2prefix "$old_subnet_mask")" dev "$interface" 2>/dev/null
}

add_new_address()
{
	prefix=$(mask2prefix "$new_subnet_mask")
	if [ -n "$new_broadcast_address" ]; then
		$IP -4 addr add "$new_ip_address/$prefix" broadcast "$new_broadcast_address" dev "$interface"
	else
		$IP -4 addr add "$new_ip_address/$prefix" dev "$interface"
	fi
	$IP link set dev "$interface" up

	$LOGGER "New IP Address ($interface): $new_ip_address"
	$LOGGER "New Subnet Mask ($interface): $new_subnet_mask"
	$LOGGER "New Broadcast Address ($interface): $new_broadcast_address"
	$LOGGER "New Routers ($interface): $new_routers"

	if [ -n "$new_routers" ] && [ "$new_routers" != "255.255.255.255" ]; then
		/usr/local/sbin/ifctl -i ${interface} -4rd -a ${new_routers}
	fi
}

delete_old_alias()
{
	if [ -n "$alias_ip_address" ]; then
		$IP -4 addr del "$alias_ip_address/$(mask2prefix "$alias_subnet_mask")" dev "$interface" > /dev/null 2>&1
	fi
}

add_new_alias()
{
	if [ -n "$alias_ip_address" ]; then
		$IP -4 addr add "$alias_ip_address/$(mask2prefix "$alias_subnet_mask")" dev "$interface"
	fi
}

fill_classless_routes()
{
	set $1
	while [ $# -ge 5 ]; do
		if [ $1 -eq 0 ]; then
			route="default"
		elif [ $1 -le 8 ]; then
			route="$2.0.0.0/$1"
			shift
		elif [ $1 -le 16 ]; then
			route="$2.$3.0.0/$1"
			shift; shift
		elif [ $1 -le 24 ]; then
			route="$2.$3.$4.0/$1"
			shift; shift; shift
		else
			route="$2.$3.$4.$5/$1"
			shift; shift; shift; shift
		fi
		shift
		router="$1.$2.$3.$4"
		classless_routes="$classless_routes $route $router"
		shift; shift; shift; shift
	done
}

delete_old_routes()
{
	if [ -n "$old_classless_routes" ]; then
		fill_classless_routes "$old_classless_routes"
		set $classless_routes
		while [ $# -gt 1 ]; do
			if [ "0.0.0.0" = "$2" ]; then
				$IP route del "$1" dev "$interface" 2>/dev/null
			else
				$IP route del "$1" via "$2" 2>/dev/null
			fi
			shift; shift
		done
		return 0;
	fi

	if [ -n "$old_static_routes" ]; then
		set $old_static_routes
		while [ $# -gt 1 ]; do
			$IP route del "$1" via "$2" 2>/dev/null
			shift; shift
		done
	fi

	/usr/local/sbin/ifctl -i ${interface} -4rd

	$IP neigh flush dev "$interface" >/dev/null 2>&1
}

add_new_routes()
{
	# RFC 3442: If the DHCP server returns both a Classless Static
	# Routes option and a Router option, the DHCP client MUST ignore
	# the Router option.
	#
	# DHCP clients that support this option (Classless Static Routes)
	# MUST NOT install the routes specified in the Static Routes
	# option (option code 33) if both a Static Routes option and the
	# Classless Static Routes option are provided.

	if [ -n "$new_classless_routes" ]; then
		fill_classless_routes "$new_classless_routes"
		$LOGGER "New Classless Static Routes ($interface): $classless_routes"
		set $classless_routes
		while [ $# -gt 1 ]; do
			if [ "0.0.0.0" = "$2" ]; then
				$IP route add "$1" dev "$interface"
			else
				$IP route add "$1" via "$2"
			fi
			shift; shift
		done
		return
	fi

	for router in $new_routers; do
		/usr/local/sbin/ifctl -i ${interface} -4rd -a ${router}

		# 2nd and subsequent default routers error out, so explicitly
		# stop processing the list after the first one.
		break
	done

	if [ -n "$new_static_routes" ]; then
		$LOGGER "New Static Routes ($interface): $new_static_routes"
		set $new_static_routes
		while [ $# -gt 1 ]; do
			$IP route add "$1" via "$2"
			if [ -z "$(/usr/local/sbin/ifctl -i ${interface} -4r)" ]; then
				/usr/local/sbin/ifctl -i ${interface} -4rd -a ${2}
			fi
			shift; shift
		done
	fi
}

add_new_resolv_conf()
{
	$LOGGER "Creating resolv.conf"

	ARGS="-i ${interface} -4nd"
	for nameserver in ${new_domain_name_servers}; do
		ARGS="${ARGS} -a ${nameserver}"
	done
	/usr/local/sbin/ifctl ${ARGS}

	/usr/local/sbin/ifctl -i ${interface} -4sd ${new_domain_name:+"-a ${new_domain_name}"}

	return 0
}

#
# Start of active code.
#

$LOGGER "Reason $reason on $interface executing"

case $reason in
MEDIUM)
	# media selection is not configurable through this path on Linux
	$IP link set dev "$interface" up
	sleep 1
	;;

PREINIT)
	delete_old_alias
	$IP link set dev "$interface" up
	/usr/local/sbin/ifctl -i ${interface} -4rd
	;;

ARPCHECK|ARPSEND)
	;;

BOUND|RENEW|REBIND|REBOOT)
	if [ -n "$new_host_name" ]; then
		$LOGGER "New Hostname ($interface): $new_host_name"
	fi

	changes="no"
	if [ -n "$old_ip_address" ]; then
		if [ -n "$alias_ip_address" -a "$old_ip_address" != "$alias_ip_address" ]; then
			delete_old_alias
			changes="yes"
		fi
		if [ "$old_ip_address" != "$new_ip_address" ]; then
			delete_old_address
			delete_old_routes
			changes="yes"
		fi
	fi
	if [ "$reason" = BOUND ] || \
	   [ "$reason" = REBOOT ] || \
	   [ -z "$old_ip_address" ] || \
	   [ "$old_ip_address" != "$new_ip_address" ]; then
		add_new_address
		add_new_routes
		changes="yes"
	fi
	if [ -n "$alias_ip_address" -a "$new_ip_address" != "$alias_ip_address" ]; then
		add_new_alias
		changes="yes"
	fi
	add_new_resolv_conf
	if [ "$changes" = "yes" ] ; then
		/usr/local/sbin/configctl -d interface newip $interface force
	fi
	;;

EXPIRE|FAIL)
	delete_old_alias
	if [ -n "$old_ip_address" ]; then
		delete_old_address
		delete_old_routes
	fi
	add_new_alias
	;;

TIMEOUT)
	delete_old_alias
	add_new_address
	sleep 1
	if [ -n "$new_routers" ]; then
		$LOGGER "New Routers ($interface): $new_routers"
		set "$new_routers"
		if ping -q -c 1 -W 1 "$1"; then
			if [ "$new_ip_address" != "$alias_ip_address" ]; then
				add_new_alias
			fi
			add_new_routes
			add_new_resolv_conf
			/usr/local/sbin/configctl -d interface newip $interface force
			exit 0
		fi
	fi
	$IP -4 addr del "$new_ip_address/$(mask2prefix "$new_subnet_mask")" dev "$interface" 2>/dev/null
	delete_old_routes
	/usr/local/sbin/configctl -d interface newip $interface
	exit 1
	;;
esac

exit 0
