#!/usr/bin/php
<?php

/*
 * MurOS interface addressing renderer for Debian (systemd-networkd).
 *
 * Translates the addressing of every assigned data interface in the
 * OPNsense-style configuration into a systemd-networkd .network unit. This
 * is the Debian replacement for the per-interface DHCP clients and ifconfig
 * calls performed by interface_configure() on FreeBSD: networkd handles the
 * DHCP lease (WAN), the static addressing (LAN) and the link state, and it
 * keeps doing so across reboots and carrier changes.
 *
 * The management interface is never rendered: it is left under the base
 * system networking (netplan/cloud-init) and may be listed in the reserved
 * file so MurOS can never lock the operator out.
 *
 * Generated files are owned by MurOS and named 10-muros-<dev>.network.
 * Stale files for interfaces that are no longer assigned are removed.
 *
 * Usage: render_networkd.php [config.xml]   (defaults to /conf/config.xml)
 */

$configFile = isset($argv[1]) ? $argv[1] : '/conf/config.xml';
$netDir = '/etc/systemd/network';
$reservedFile = '/usr/local/etc/muros/reserved.conf';

if (!is_readable($configFile)) {
    fwrite(STDERR, 'config not readable: ' . $configFile . PHP_EOL);
    exit(1);
}
$cfg = simplexml_load_file($configFile);
if ($cfg === false || !isset($cfg->interfaces)) {
    fwrite(STDERR, 'no interfaces section in config' . PHP_EOL);
    exit(1);
}

function dev_exists($dev)
{
    return $dev !== '' && is_dir('/sys/class/net/' . $dev);
}

function reserved_devices($file)
{
    if (!is_readable($file)) {
        return array();
    }
    $out = array();
    foreach (file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        $line = trim($line);
        if ($line !== '' && $line[0] !== '#') {
            $out[$line] = true;
        }
    }
    return $out;
}

$reserved = reserved_devices($reservedFile);
@mkdir($netDir, 0755, true);
$wanted = array();

foreach ($cfg->interfaces->children() as $key => $node) {
    $dev = trim((string)$node->if);
    if (!dev_exists($dev) || isset($reserved[$dev])) {
        continue;
    }
    if (empty((string)$node->enable)) {
        continue;
    }

    $ip4 = trim((string)$node->ipaddr);
    $sub4 = trim((string)$node->subnet);
    $gw4 = trim((string)$node->gateway);
    $ip6 = trim((string)$node->ipaddrv6);
    $sub6 = trim((string)$node->subnetv6);
    $mtu = trim((string)$node->mtu);

    $v4dhcp = ($ip4 === 'dhcp');
    $v6dhcp = ($ip6 === 'dhcp6');
    $v4static = filter_var($ip4, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4) && ctype_digit($sub4);
    $v6static = filter_var($ip6, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) && ctype_digit($sub6);

    if ($v4dhcp && $v6dhcp) {
        $dhcp = 'yes';
    } elseif ($v4dhcp) {
        $dhcp = 'ipv4';
    } elseif ($v6dhcp) {
        $dhcp = 'ipv6';
    } else {
        $dhcp = 'no';
    }

    $lines = array();
    $lines[] = '# Generated by MurOS render_networkd.php. Do not edit by hand.';
    $lines[] = '[Match]';
    $lines[] = 'Name=' . $dev;
    $lines[] = '';
    if ($mtu !== '' && ctype_digit($mtu)) {
        $lines[] = '[Link]';
        $lines[] = 'MTUBytes=' . $mtu;
        $lines[] = '';
    }
    $lines[] = '[Network]';
    $lines[] = 'DHCP=' . $dhcp;
    $lines[] = 'ConfigureWithoutCarrier=yes';
    $lines[] = 'IPv6AcceptRA=' . ($v6dhcp ? 'yes' : 'no');
    if ($v4static) {
        $lines[] = 'Address=' . $ip4 . '/' . $sub4;
    }
    if ($v6static) {
        $lines[] = 'Address=' . $ip6 . '/' . $sub6;
    }
    if ($v4static && filter_var($gw4, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
        $lines[] = 'Gateway=' . $gw4;
    }
    $lines[] = '';

    $target = $netDir . '/10-muros-' . $dev . '.network';
    file_put_contents($target, implode(PHP_EOL, $lines));
    chmod($target, 0644);
    $wanted[$target] = true;
    echo 'rendered ' . $node->getName() . ' -> ' . $dev . ' (dhcp=' . $dhcp . ($v4static ? ', ' . $ip4 . '/' . $sub4 : '') . ')' . PHP_EOL;
}

/* Remove MurOS-owned files for interfaces no longer assigned. */
foreach (glob($netDir . '/10-muros-*.network') as $existing) {
    if (!isset($wanted[$existing])) {
        @unlink($existing);
        echo 'removed stale ' . $existing . PHP_EOL;
    }
}

exec('systemctl is-active --quiet systemd-networkd', $o, $rc);
if ($rc !== 0) {
    exec('systemctl enable --now systemd-networkd 2>&1');
}
exec('networkctl reload 2>&1', $o2, $rc2);
exit(0);
