[list]
command:/usr/local/sbin/pluginctl -S
parameters:
type:script_output
message:request service list

[start]
command:/usr/local/sbin/pluginctl -s
parameters:%s start %s
type:script_output
message:start service %s

[stop]
command:/usr/local/sbin/pluginctl -s
parameters:%s stop %s
type:script_output
message:stop service %s

[restart]
command:/usr/local/sbin/pluginctl -s
parameters:%s restart %s
type:script_output
message:restart service %s
