#!/bin/sh

# Copyright (C) 2005 Bill Marquette <bill.marquette@gmail.com>
# Copyright (C) 2005 Scott Ullrich <sullrich@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

. /usr/local/opnsense/scripts/firmware/config.sh

DESTDIR="/usr/local/etc"
WORKDIR="/tmp/bogons"

# Public Team Cymru fullbogons feeds. The OPNsense build pulled a signed
# bogons.txz from its own mirror (fetch + opnsense-verify); MurOS has no such
# mirror, so these are plain HTTPS downloads validated against the system trust
# store.
URL_V4="https://www.team-cymru.org/Services/Bogons/fullbogons-ipv4.txt"
URL_V6="https://www.team-cymru.org/Services/Bogons/fullbogons-ipv6.txt"

CURL="curl -fsS --connect-timeout 30 --max-time 300"

echo "bogons update starting" | logger

rm -rf ${WORKDIR}
mkdir -p ${WORKDIR}

fetch_one()
{
    URL=${1}
    OUT=${2}

    if ! ${CURL} -o "${WORKDIR}/${OUT}" "${URL}"; then
        echo "bogons update cannot download ${URL}" | logger
        return 1
    fi
}

update_bogons()
{
    SRC=${1}
    DST=${2}
    shift 2

    echo "# private network exclusions generated by MurOS" > ${WORKDIR}/${DST}

    # private and pseudo-private networks are excluded here because they are
    # operated by a separate GUI option
    for NET in ${@}; do
        echo "!${NET}" >> ${WORKDIR}/${DST}
    done

    cat ${WORKDIR}/${SRC} >> ${WORKDIR}/${DST}
    mv ${WORKDIR}/${DST} ${DESTDIR}/${DST}
}

# The pf table-entries sizing checks and the live "pfctl -t ... -T replace"
# reloads are gone: the files are written unconditionally and the firewall
# filter loads them into its tables on the next reload.
if fetch_one "${URL_V4}" fullbogons-ipv4.txt; then
    update_bogons fullbogons-ipv4.txt bogons 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 127.0.0.0/8 100.64.0.0/10 169.254.0.0/16
    echo "Bogons V4 file updated: $(wc -l < ${DESTDIR}/bogons) entries" | logger
fi

if fetch_one "${URL_V6}" fullbogons-ipv6.txt; then
    update_bogons fullbogons-ipv6.txt bogonsv6 fd00::/8 fe80::/10 ::/128
    echo "Bogons V6 file updated: $(wc -l < ${DESTDIR}/bogonsv6) entries" | logger
fi

echo "update bogons is ending the update cycle" | logger
