###################################################################
# Local syslog-ng configuration filter definition [pkg].
###################################################################
{# MurOS: the package manager is apt and dpkg, there is no pkg #}
filter f_local_pkg {
    program("apt") or program("apt-get") or program("apt-listchanges")
    or program("dpkg") or program("unattended-upgrades");
};
