[start]
command:/usr/bin/monit -c /usr/local/etc/monitrc
type:script
message:starting monit

[stop]
command:/usr/bin/monit -c /usr/local/etc/monitrc quit
type:script
message:stopping monit

[status]
command:/usr/bin/monit -c /usr/local/etc/monitrc status
errors:no
type:script_output
message:get monit status

[restart]
command:/usr/bin/monit -c /usr/local/etc/monitrc reload 2>/dev/null || /usr/bin/monit -c /usr/local/etc/monitrc
type:script
message:restarting monit
description:Restart Monit service

[reload]
command:/usr/bin/monit -c /usr/local/etc/monitrc reload
type:script
message:reload monit configuration

[check]
command:/usr/local/opnsense/scripts/monit/setup.sh; /usr/bin/monit -c /usr/local/etc/monitrc -t 2>&1
errors:no
type:script_output
message:testing monit configuration
