[reload]
command:/usr/local/opnsense/scripts/shaper/tc_apply.py apply
parameters:
type:script
message:reloading the traffic shaper

[flush]
command:/usr/local/opnsense/scripts/shaper/tc_apply.py flush
parameters:
type:script
message:flushing the traffic shaper

[stats]
command:/usr/local/opnsense/scripts/shaper/tc_apply.py statistics
parameters:
type:script_output
message:request traffic shaper stats

[notes]
command:/usr/local/opnsense/scripts/shaper/tc_apply.py notes
parameters:
type:script_output
message:request what the traffic shaper cannot translate
